### ISSUE TITLE
Expand SQL coverage to pushdown all multi-shard queries with colocated tables and subselects

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1204]
Citus currently provides full SQL coverage for the multi-tenant use case.

For the operational analytics use case, when the user creates multiple colocated tables and has complex subselects, we provide them with rules in how they need to write their queries. This issue tracks expanding our SQL coverage to include all SQL queries that touch colocated tables and subselects.

We're tracking example customer queries in two internal documents (Raw Queries: Expanding SQL Coverage, Summary: Expanding SQL Coverage). I'm opening this issue to track our progress on this task.

**Comment by onderkalaci** [comment]
@ozgune We only support co-location for hash distributed tables. Is the scope of this issue hash-distributed tables? In other words, existing logic allows range distributed tables and what is our goal for it?

**Comment by onderkalaci** [comment]
As we're about to start the implementation, I'd like to list the items we need to implement:

- [ ] Improve physical planner to use INSERT ... SELECT logic
  - [ ] Use the logic in the prototype [branch](https://github.com/citusdata/citus/tree/subquery_pushdown_proper)
  - [ ] Use the improved shard pruning logic in the other branch (see #1245)
  - [ ] Use joininfo in restrictions (see #1244)
  - [ ] Also ensure that these changes do not break anything in router planner given that we're adding a parameter to restrict information.

- [ ]  Subquery pushdown flag
    - [ ] We should remove the subquery pushdown flag. Basically, we should have a mechanism to fall back to regular multi-planner if the subquery is not pushable. 
         - [ ] This is mostly important for single table repartition subqueries to work. But, also consider the interactions with views as well.
- [ ] Unsupported Table Combinations / Having multiple range table entries in the top level subqueries
    - [ ] Currently, subquery pushdown disallows JOINing subqueries with relations. Similarly, disallows joining more than two tables/subqueries as well. `ErrorIfUnsupportedTableCombination()` seems completely irrelevant with the new approach. We should be able to JOIN any number of tables/subqueries.
    - [ ] In the existing implementation, we disallow having more than one target list entry in the top level subquery. See the lines `subqueryRangeTableEntry = (RangeTblEntry *) linitial(subqueryEntryList);` in the logical planner. We should definitely relax this constraint and allow multiple range table entries in the top level subquery.

- [ ] Subqueries without aggregates/GROUP bys
    - [ ] In the current implementation, we disallow subqueries without agg/GROUP BYs. See `ErrorIfSubqueryNotSupported()`. I don’t see any reason for not allowing subqueries with agg/GROUP BYs. Investigate more from the correctness perspective. If there is nothing related with correctness, remove these checks.

- [ ]  Subqueries in WHERE clause (see #1244 for the example queries that we could allow)
     - [ ] Currently, we error out when there is a subquery in WHERE clause. We should allow subqueries in WHERE clause. If possible, we should only allow EXPR_SUBLINK which is the only sublink we could push down.

- [ ] Reference Table support:
     - [ ] The current implementation of subquery push down does not take reference tables into account. We should be allowing reference tables, which looks straightforward.

 - [ ] Composite Keys
      - [ ]  Existing subquery pushdown logic (or in general Citus planner) counts the following as partition key equality: (composite_key.id = composite_key.id AND composite_key.id_2 = composite_key.id_2)   where composite key consists of (id, id_2). Do we want to keep this behaviour?
      - [ ] In the prototype, the equality should be written as: composite_key_col_1 = composite_key_col_2


- [ ] UNIONs
     - [ ] Consider relaxing ErrorIfUnsupportedUnionQuery(). In other words, allow unions to have different filters. 
      - [ ] Consider why we’ve disallowed UNION ALL. If not related to the correctness, remove that check as well.
     - [ ] In UNION ALL case, we could even allow subqueries without partition key on the target list?
     - [ ] What about EXCEPT/Intersect?

 - [ ] Lateral Joins:
     - [ ] We need to consider two things for the lateral JOINs. 
          - [ ] Firstly, the subquery pushdown prototype does not work with LATERAL JOINs. Thus, understand and fix it.
          - [ ] Secondly, investigate SupportedLateralQuery() function and keep the limitations that are related to the correctness of pushing down subqueries.

 - [ ] Views
     - [ ] Now that we have some more subquery pushdown, we should support view for such queries? If so, lets add regression tests.

 - [ ] Shard distribution checks:
     - [ ] Namely ErrorIfUnsupportedShardDistribution() function. We could improve the check for hash partitioned tables by simply checking the colocationIds.

 - [ ] Filters on the LEAF queries:
     - [ ] In the existing implementation, we specifically ask users to have the same filter on the LEAF queries.
     - [ ] So, we should probably completely remove ErrorIfUnsupportedFilters() function.

 - [ ] LIMIT/LIMIT OFFSET
     - [ ] From the correctness perspective, we could only allow these clauses in the toplevel query.
     - [ ] Should we introduce a GUC to allow these clauses in the lower levels?

**Comment by mtuncer** [comment]
@onderkalaci 
> [ ] Enable router planner for append partitioned tables. Given that we're planning to use router planner for subquery pushdown, the router planner should work with append partitioned tables.

Here you meant range partitioned tables  not append right ?

**Comment by ozgune** [comment]
We have the core functionality merged into Citus 6.2 for broader SQL coverage. I'm removing the 6.2 milestone from this issue; and we'll separately track sub-items listed in this issue.
