### ISSUE TITLE
Support Follower Clusters

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#1528]
Work to be done
- [x] (#1518) Add `pg_dist_node.nodecluster` column
  - Give every node a cluster which it is a part of, default to 'default' and make sure no existing behavior changes.
- [x] (#1530) Add `citus.cluster_name` GUC, and all functions only see nodes which are a part of the current cluster
- [x] (#1540) Add `citus.use_secondary_nodes`, which allows the coordinator in the follower cluster to use the nodes in the follower cluster
- [x] (#1542) Consider adding a `master_add_secondary_node` function
- [x] (#1543) Consider adding a test that you can run queries from a streaming replica?

Questions

- [x] Should you be allowed to add `primary` nodes to non-`default` clusters?

**Comment by lfittl** [comment]
@lithp @ozgune Can this issue be closed, or is there still work required to support follower clusters?

**Comment by lithp** [comment]
As far as I know it can be closed.
