### ISSUE TITLE
Recursive planning and execution using pull-push

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1804]
Most of Citus’ limitations in terms SQL support lie in subqueries and CTEs. Very often, the CTE or subquery itself is a query that could be planned and executed by on its own. One way to rapidly expand our SQL support is to recognise subqueries that cannot be planned using existing planners and plan and execute them independently, writing the results to an intermediate data structure that is then used in subsequent steps.

For instance, a query for the distinct number of sessions on the top 20 most visited pages:

```sql
SELECT
  page_id, count(distinct session_id)
FROM
  visits
WHERE
  page_id IN (SELECT page_id FROM visits GROUP BY page_id ORDER BY count(*) DESC LIMIT 20) 
GROUP BY
  page_id;
```

The LIMIT in the subquery prohibits subquery pushdown. If the table is not sharded by page_id, then the GROUP BY also prohibits subquery pushdown. However, the subquery itself can be executed as a distributed query:

```sql
SELECT page_id FROM visits GROUP BY page_id ORDER BY count(*) DESC LIMIT 20
```

We can execute this query separately and write the results to an intermediate data structure that is made available on the workers. In the outer query, the subquery is replaced by the intermediate result, e.g.:

```sql
SELECT
  page_id, count(distinct session_id)
FROM
  visits
WHERE
  page_id IN (SELECT * FROM intermediate_result(...) AS res(page_id int)) 
GROUP BY
  page_id;
```

A downside of recursive planning is that it prescribes a certain execution order, while an optimiser that considers the whole plan might find a more efficient alternative. However, it puts us in a position where we can gradually improve the underlying planners, which would reduce the number of recursions.

## Pull and push intermediate result

A simple implementation of recursive planning that would significantly enhance our SQL support is to execute unsupported subqueries and CTEs as regular queries on the coordinator and then push the results back into all relevant worker nodes and treat the result as a reference table that can be used in joins. This approach covers queries which require a merge step such as the LIMIT query above, as well as subqueries on local tables and functions.

A more sophisticated approach is to treat the intermediate result as a distributed table, which is sharded based on how the query result is joined. This improves efficiency and support for outer joins, but has additional implementation complexity.

We may want to use intermediate files instead of intermediate tables, because we cannot create intermediate tables in follower clusters. For small result sets (e.g. the LIMIT example), we could also consider including the results in the SQL query of the next step as VALUES or as an array parameter.

**Comment by marcocitus** [comment]
### Task breakdown

- [ ] Treat functions and constant queries like reference tables ("recurring tuples") #1805

- [ ] Infrastructure for moving around intermediate results ("pull push") #1829

- [ ] Real-time executor improvements
  - [ ] Reuse connections within a transaction block (#1785)
  - [ ] Open transaction blocks on workers to read transaction-specific intermediate results (#1841)

- [ ] Union pushdown improvements
  - [ ] Allow joins in subqueries of unions (#1839)
  - [ ] Allow different partition column filters in subqueries of unions (#1840)
 
- [ ] Add functions for filtering of planner restriction context (#1833)

- [ ] Recursive planning PRs with relevant regression tests:
  - [ ] Recursively Plan CTEs
  - [ ] Recursively plan subqueries that require a merge step (e.g. LIMIT, GROUP BY on non-partition column)
  - [ ] Recursively plan children of non-pushdownable set operations
  - [ ] Recursively plan subqueries that are on the inside of an outer join that has recurring tuples on the outside
  - [ ] Recursively plan the subqueries in non-co-located joins between subqueries

- [ ] Limit the size of intermediate results to avoid running out of disk space due to a bad subquery.

- [ ] If `task_executor_type` is `'real-time'`, dynamically switch to task-tracker for re-partition queries unless `task_tracker_query_log_level` is set to `ERROR` (the default)

- [ ] Performance improvements
  - [ ] Load-balance 0-shard router queries across all nodes
  - [ ] Use `set_rel_pathlist_hook` to set cost and row count of intermediate result function calls to improve postgres plans
  - [ ] Only send intermediate results to worker nodes that will actually read it
  - [ ] Execute queries with only intermediate results locally (instead of router executor)

- [ ] Add an option to start transaction blocks in repeatable read mode such that different subqueries read from the database using the same snapshot (per shard placement).

- [ ] Improve error messages. Because we plan some subqueries by calling the planner from the top, the error messages may not make sense to the user. 

### Related tasks

Some SQL features are supported in subquery pushdown, but not in top-level queries. This will be confusing to users :

- [ ] Use "subquery" pushdown to plan other queries (#1706). The subquery pushdown planner is also able to plan regular queries and would be able to provide support for features that are not supported in the logical planner or have convoluted code paths such as:
  - [ ] unsupported clause types
  - [ ] outer joins
  - [ ] union

- [ ] Top-level window functions are not supported in top-level queries and therefore also not in subqueries when they are recursively planned (#1847)

**Comment by marcocitus** [comment]
Since most of the items have been addressed, closing in favour of more specific issues (#3200 and #3217).
