### ISSUE TITLE
Get adaptive executor to production ready state

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2665]
We've a prototype for unified executor (#2435 and the main issue: https://github.com/citusdata/citus/issues/1273). The branch implements all the main required features. However, it still requires a lot of effort to get into the production ready state.

We split the whole task into several sub-tasks to get things done in parallel and have smaller granularities to review the sub-tasks.

As we dive deeper into the tasks, we may update the issue to reflect our investigations.

#### Many of the failures are as simple as adjusting the regression tests to produce consistent results over different executions. Some other failures are just because we've forked the branch few releases before and thus some features (like foreign keys to reference tables) are not considered in the branch. So, make sure to fix those smallish integration issues. There are few errors that needs closer look that I've not able to understand in the first glance.

- [x] Regression tests may fail just because execution order of the queries on the shards changes. Real-time executor pretty much always follows the same execution order. So, even if a query misses an `ORDER BY`, the results don't change on every execution.
   - [x] Simply switch to [unified_executor](https://github.com/citusdata/citus/compare/unified_executor?expand=1) branch and run regression tests few times to gather randomly changing regression test outputs. Related PRs #2659, #2661, #2657. There might be some more of these.

   - [x] The harder case is to get consistent output for queries with `RETURNING` clause (`RETURNING` doesn't support `ORDER BY`). Two approaches we could think of: (a) Change the data/queries such that the results returns a single row or multiple of the same rows (b) Wrap the query into a CTE, and add `ORDER BY` to the cte. Note that the latter sounds like changing the query execution semantics so be cautious. Similarly, for the former, we should make sure that we gather results from multiple shards (e.g., don't return distribution key only) to keep the execution semantics the same. (c) Sort tuplestore #2677

- [x] Unified executor does not create intermediate files. `multi_query_directory_cleanup.sql` test has the assumption of intermediate folders/files. We should adjust the tests so that they don't fail (#2728).

- [x] With the new executor, the intermediate data sizes change since we're avoiding `COPY`. See `limit_intermediate_size.sql` test. Related PR: #2662

- [x] `master_modify_multiple_shards()` seems to have a bug. It is probably as simple as not setting the number of tuples that are modified. Related PR: #2660

- [x] Marco has started working on this branch few releases before. Thus, the current prototype does not consider few of the newest Citus features. We should make sure to enable them: #2688 and #2692 
    - [x] Foreign keys to reference tables. Directly effected tests: `foreign_key_restriction_enforcement.sql`, `relation_access_tracking.sql`, `foreign_key_to_reference_table.sql`, `validate_constraint.sql` and `multi_reference_table.sql` (potentially few more). 
 - [x] Fast-path router queries (`fast_path_router_modify.sql`) fails when there is a parameter on the distribution key on  `ExtractParametersFromParamListInfo()` function.  Also, similar error on `multi_router_planner_fast_path.sql` (#2672).
    
- [x] `multi_subtransactions.sql` tests are failing. My very brief understanding is that we're failing to pick the right connection for accessing the save points on the workers. It could be great if Hadi can start looking into this. [Hadi, in progress]. See #2673 and #2676

- [x] The code aims to do the connection initilizations async (e.g., `StartNodeUserDatabaseConnection()` and `PQconnectPoll()` are seperated). Also, the code is smart about using connections. Say, the pool size is 4, we do 4 `StartNodeUserDatabaseConnection()`. And, due to the load (or anything else) if you got only 1 connection fully established, all the queries are sent over that connection. And, if the whole execution ends before we establish the other connections fully, in the worker logs we see `incomplete packet startup`. We should probably keep track of `not fully established` connections and properly terminate those. An example (fixed by #2808):
```SQL
postgres=# BEGIN;                                                                                                                                                                  
BEGIN
Time: 0.238 ms
postgres=# INSERT INTO agg_results (user_id, agg_time, value_2_agg)                                                                                                                
SELECT
    user_id,
    user_lastseen,
    array_length(event_array, 1)
FROM (
    SELECT
        user_id,
        max(u.time) as user_lastseen,
        array_agg(event_type ORDER BY u.time) AS event_array
    FROM (
        SELECT user_id, time, value_3 as val_3
        FROM users_table
        WHERE
        user_id >= 10 AND user_id <= 70 AND
        users_table.value_1 > 10 AND users_table.value_1 < 12
        ) u LEFT JOIN LATERAL (
          SELECT event_type, time
          FROM events_table, (SELECT random()::int as x) as f
          WHERE user_id = u.user_id AND
          events_table.event_type > 10 AND events_table.event_type < 12
        ) t ON true
        GROUP BY user_id
) AS shard_union
ORDER BY user_lastseen DESC;
INSERT 0 0
Time: 39.480 ms
postgres=# INSERT INTO test SELECT s, s FROM generate_series(1,100) s;
WARNING:  connection error: localhost:9701
ERROR:  could not connect to any active placements
```

- [x] There are some test failures because of the errors one replica of replicated/reference tables (see #2713)
    - [x] `muli_alter_table_statements.sql` unexpectedly fails. The scenario is that on a single shard table, a transaction fails on `COMMIT` because of a trigger throwing an error. Insead of getting an error and rolling back, we get `WARNING:  failed to commit critical transaction on localhost:57638, metadata is likely out of sync`. (#2685)
    - [x] `multi_modifying_xact.sql` fails because some expected `WARNING`s are turned into `ERROR`s. (#2713)
    - [x] `multi_router_planner.sql` expects the placements to have `shardstate = 3`, where we get `shardstate = 1`. Looks like a similar failure as described above. (#2713)
    - [x] `multi_mx_modifying_xacts.sql` shows a similar behaviour (#2713)
  

- [x] Lots of tests fail because there are lots of assumptions about 1-1 mapping of connection to placement in the tests. We might consider implementing `force 1 shard to 1 connection` mode, and make sure the tests pass. Later, we can consider introducing some more tests specifically targeting the unified executor's specific behaviours [#2666].

    - [x] `real_time_transaction.sql` is failing because it has the assumption that each worker session can safely call `pg_advisory_lock()`. We could consider using `pg_advisory_xact_lock()` instead. However, a more comprehensive solution we have in mind is different. Add a GUC which enforces 1-1 placement-connection mapping as the current parallel executors does.
    - [x] `multi_transaction_recovery.sql` is failing because it assumes that the DDL would open # shards connections. We should force 1-1 mapping to pass the tests. 
    - [x] Isolation tests fails because some tests rely on the workers being blocked due to parallel connections
    - [x] Similar to failure tests, there are lots of assumptions about 1-1 mapping of connection to placement in the isolation tests, so without it the tests fail very often.
    - [x] `sequential_modifications.sql` assumes that parallel executions always opens a single connection per placement. We should change that assumption in the tests.

- [x] I get the following error on the isolation tests --  always on the same test (even after make-clean) - #2730:
```
WARNING:  detected write past chunk end in PortalContext 0x7f81a20875b8
WARNING:  problem in alloc set PortalContext: req size > alloc size for chunk 0x7f81a2087610 in block 0x7f81a2086200
WARNING:  problem in alloc set PortalContext: bad size 0 for chunk 0x7f81a2087610 in block 0x7f81a2086200
WARNING:  problem in alloc set PortalContext: req size > alloc size for chunk 0x7f81a2087628 in block 0x7f81a2086200
WARNING:  problem in alloc set PortalContext: bogus aset link in block 0x7f81a2086200, chunk 0x7f81a2087628
WARNING:  problem in alloc set PortalContext: bad single-chunk 0x7f81a2087721 in block 0x7f81a2086200
WARNING:  problem in alloc set PortalContext: bogus aset link in block 0x7f81a2086200, chunk 0x7f81a2087721
WARNING:  problem in alloc set PortalContext: found inconsistent memory block 0x7f81a2086200
WARNING:  problem in alloc set PortalContext: req size > alloc size for chunk 0x7f81a2087610 in block 0x7f81a2086200
WARNING:  problem in alloc set PortalContext: bad size 0 for chunk 0x7f81a2087610 in block 0x7f81a2086200
WARNING:  problem in alloc set PortalContext: req size > alloc size for chunk 0x7f81a2087628 in block 0x7f81a2086200
WARNING:  problem in alloc set PortalContext: bogus aset link in block 0x7f81a2086200, chunk 0x7f81a2087628
WARNING:  problem in alloc set PortalContext: bad single-chunk 0x7f81a2087721 in block 0x7f81a2086200
WARNING:  problem in alloc set PortalContext: bogus aset link in block 0x7f81a2086200, chunk 0x7f81a2087721
WARNING:  problem in alloc set PortalContext: found inconsistent memory block 0x7f81a2086200
```

- [x] It looks like `idleConnectionCount` is unnecessarly incremented on `REMOTE_TRANS_INVALID`. Make sure that and fix it. See #2740 
- [x] Inserts going to two different shards do not use 2PC, see the regression test `multi_mx_transaction_recovery.sql`, and another example here (see #2713):
```SQL
postgres=# INSERT into users_table (user_id) VALUES (1);
DEBUG:  query before rebuilding: (null)
DEBUG:  query after rebuilding:  INSERT INTO public.users_table_102009 (user_id) VALUES (1)
DEBUG:  Creating router plan
DEBUG:  Plan is router executable
DETAIL:  distribution column value: 1
DEBUG:  assigned task 0 to node localhost:9701
DEBUG:  opening 1 new connections to localhost:9701
DEBUG:  established connection to localhost:9701
LOG:  issuing BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;SELECT assign_distributed_transaction_id(0, 1, '2019-04-17 12:59:03.915119+03');
DETAIL:  on server localhost:9701
LOG:  issuing INSERT INTO public.users_table_102009 (user_id) VALUES (1)
DETAIL:  on server localhost:9701
INSERT 0 1
postgres=# INSERT into users_table (user_id) VALUES (2);
DEBUG:  query before rebuilding: (null)
DEBUG:  query after rebuilding:  INSERT INTO public.users_table_102032 (user_id) VALUES (2)
DEBUG:  Creating router plan
DEBUG:  Plan is router executable
DETAIL:  distribution column value: 2
DEBUG:  assigned task 0 to node localhost:9700
DEBUG:  opening 1 new connections to localhost:9700
DEBUG:  established connection to localhost:9700
LOG:  issuing BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;SELECT assign_distributed_transaction_id(0, 1, '2019-04-17 12:59:03.915119+03');
DETAIL:  on server localhost:9700
LOG:  issuing INSERT INTO public.users_table_102032 (user_id) VALUES (2)
DETAIL:  on server localhost:9700
INSERT 0 1
postgres=# COMMIT;
LOG:  issuing COMMIT
DETAIL:  on server localhost:9701
LOG:  issuing COMMIT
DETAIL:  on server localhost:9700
COMMIT
```

- [x] For multi-row INSERTs, we've a concept of `Sequential Execution`. The concept consists of two things: (a) One connection per node (b) Each task is executed sequentially, so something like `for t in taskList: Execute(t)`. This is mostly implemented for high throughput multi-row INSERTs/UPSERTs. If we do not have sequential execution, concurrent multi-row upserts could easily form a distributed deadlock if the upserts touch the same rows. The unified executor currently does not have a such concept. Note that setting the `worker_pool_size` to `1` do only cover (a), not (b). See #2735

- [x] We do not acquire executor locks. For example, running the following query via pgbench in parallel with the new executor `update users_table SET value_1 = value_1 + 1;`, we end-up with distributed deadlocks. In the end, the behaviour is changing. (#2752)

- [x] Implement a GUC which enables switch between unified executor and the existing executors. This item should also consider setting the custom scans properly. For example, `CitusModifyBeginScan` does some important stuff, which we should continue doing with unified executor. Fixed by #2799

- [x] SELECT FOR UPDATE on reference tables should be treated as a modification in the sense that the query should be sent to all replicas. In unified executor, we only send it to a single placement (#2768).

#### In my first iteration, I couldn’t find an easy way to split the change into smaller pieces and get them one-by-one to the master. I’m still considering various options for doing that. But, please note that there is a possibility that we’d end up merging a big part of the changes in the same pull request. The challenge here is that the executor is pretty smart (and conservative) about opening new connections. Thus, the task assignments to the connections, establishing new connections and transaction management is tightly coupled.
 
- [x] Add a README that explains the high level architecture. Currently, each individual struct/function have short descriptions. However, the high-level architecture has not been explained in any place. So, adding a readme should ease reading the code. #2792
- [x] Can we split the code into smaller pieces and get them one-by-one? We did this as much as possible, for example, we've merged COPY into master and then rebased the adaptive executor onto master.
- [x] Discuss more on the user facing APIs, some [notes] (#2779)(https://docs.google.com/document/d/1MuJ6V6E7X_25J4kFN0uXFiFwLMcq8h4I0PGJd-XqqKA/edit):
    - [x] Should we expose the `pool_size` per worker - per distributed query? Could we automatically pick it for the user depending on the load - query execution times? We use `citus.max_adaptive_executor_pool_size`
    - [x] Caching the connections have a dramatic effect on the performance/throughput. How should we expose the connection caching to the user? Should we do it automatically? Fixed by #2716

- [x] Currently `create_distributed_table()` and `DROP distributed_table` has a completely separate way(s) of execution tasks. Could we modify those code-paths to use the new executor? (#2770).
     - Note that we decided not to touch DROP

- [ ] Can we adjust the pool sizes automatically? In the end, the user would pick the `max_worker_pool_size`, however, instead of blindly going up-to that level, could Citus adjust the pool size depending on the load? Likely to be 8.4 item.

    - [x] One idea we've discussed is the `Slow Start` approach that TCP implements to control the congestion/load. Citus would first start using one connection to the worker node. It'd wait some time (e.g., `10ms`), if in the mean time we successfully establish the first connection (and maybe get at least one of the query result back), we start establishing one more connection. We do it until we reach `max_worker_pool_size`.  (#2779)
    - [ ] The other idea could be to count the number of outgoing connections globally (e.g., across sessions). Depending on the total load on the workers, we smartly control the number of connections the executions use. If there are too many concurrent parallel queries, use smaller pool sizes, else go up to `max_pool_size`

- [x] Go over all the flags/params to waitEvents/waitFlags, and make sure that we've covered various different edges that are covered with the current executors (#2783).

- [x] Should we keep the existing real-time and router executors behind a feature flag? Executor can be changed via `citus.task_executor_type` #2799 

- [x] Try to simplify the code.

- [x] Add new regression tests that'd specifically benefit from the executor
    - [x] Complex transaction blocks
    - [x] Failure tests (with different replication factors - reference tables as well)
    - [x] Do we need any extra isolation tests?

- [x] Work on when to mark connections `SESSION_LIFESPAN`. The prototype currently always marks all the connections with `SESSION_LIFESPAN` meaning that the connections are cached as long as the psql session lives -- same as the router executor does. However, that might end up keeping lots of connections open to the worker nodes. So, be smart about when/how to mark the connections as `SESSION_LIFESPAN` (#2716)

- [x] The unified executor may regress for certain types of distributed queries. The most notable ones is that [modifying ctes followed by an coordinator insert/select](https://github.com/citusdata/citus/blob/master/src/test/regress/sql/with_dml.sql#L85-L108). The reason is that the previous modifications might use the same connections for modifying the same placements. However, the final coordinator INSERT/SELECT would require 1 connection per placement. We should probably automatically detect these cases and force 1 connection per placement in advance. See #2697, fully fixed by #2780

- [x] Explain doesn't rely on the new executor. 

- [ ] Come-up with a small document which explains all the behavioral differences that the unified executor brings.

## Phase 3: Extensively test the new executor

- [x] We should understand our product's behavior in-depth. Create a report especially for real-time queries with two dimensions (a) Different number of concurrent queries  (b) Different pool sizes
    - [x] Comparing with the current real-time executor should be fun.
- [x] Run benchmarks involving various different types of queries for a very long time. This is to make sure that we don't have any memory leaks. Some tests that we should first run independently and later in combination with each other: (a) Real-time select (b) Real-time selects that involve failures on the worker nodes (e.g., division by zero with some frequency) (c) Multi shard modifications with/without RETURNING (d) Multi-shard modifications that involve failures on the worker nodes
- [x] Make sure that online rebalancing, offline rebalancing and tenant isolation "just works" as it used to be.
- [x] Make sure that distributed deadlock detection "just works" as it used to be.
- [x] Test with/without pgbouncers. Change pgbouncer pool-sizes from very small to very large.
- [x] Test on different cloud providers

## Misc

- [x] Shall we consider a new name for `unified executor`? `Unified` covers one part of the story where we unified multiple executors into one. The other side of the story is that we'd be able to do resource management / throttling by adjusting the pool size. The latter sounds more important  to me.
    - We've finalized the name to `Adaptive Executor`, see internal e-mail thread for the naming discussions.

**Comment by marcocitus** [comment]
> So, be smart about when/how to mark the connections as SESSION_LIFESPAN.

I think we should remove the SESSION_LIFESPAN flag altogether and change AfterXactConnectionHandling to keep a connection open. That will make it easier to be smarter (e.g. keep a configurable number of connections open).

This can be done separately from the unified executor.

**Comment by onderkalaci** [comment]
>I think we should remove the SESSION_LIFESPAN flag altogether and change AfterXactConnectionHandling to keep a connection open. That will make it easier to be smarter (e.g. keep a configurable number of connections open).
This can be done separately from the unified executor.

Thanks @marcocitus, we've merged it now with #2716 to the master branch.

**Comment by marcocitus** [comment]
Remaining item covered by #3116
