### ISSUE TITLE
Problems with EL/OL 6 builds

### ISSUE THREAD

**Issue by hanefi** [citusdata/citus#3108]
This issue aims to list issues related with builds on EL/OL 6 distros.

## Errors:
- [x] Redefinition of typedef - Build fails on EL/OL 6 #3107

## Warnings:
- [x] Shadowed global variables in redhat libraries #2839
- [x] Unrecognized command line option warning in EL/OL 6 #3106

**Comment by jasonmp85** [comment]
I think the command-line option stuff is something we can (and have) ignored, but the other two are probably C cleanliness issues it's worthwhile to just fix.

**Comment by hanefi** [comment]
Related: #3153

**Comment by JelteF** [comment]
The command line option warning is fixed on master by: https://github.com/citusdata/citus/pull/3128

**Comment by JelteF** [comment]
All fixed now on master

**Comment by hanefi** [comment]
Closing this one, as all the listed items are fixed
