### ISSUE TITLE
Regression test improvements

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#347]
I'm creating this issue to track improvements related to Citus' regression tests in one place.

We currently have about ten open issues that relate to regression tests. (continuously edited)
- [ ] Issue #1828 suggests that we should add some tests with large number of shard_counts.
- [ ] Issue #1908 relates to changing deprecated `master_create_*` APIs with `create_distributed_table`.
- [ ] Issue #1909 relates to removing explicit calls, where we reduced the shard count to 4 to speed up regression tests.
- [ ] Issue #1910 relates to evaluating our regression test coverage split between append, hash, and range distributed tables.
- [ ] Issue #1911 relates to replacing short `COPY` with `INSERT` to improve regression test runtime performance.
- [ ] Issue #325 relates to cleaning up the code in `pg_regress_multi`.
- [x] Issue #253 relates to exercising shard fetching functionality for broadcast joins as part of our regression tests suite.
- [ ] Issue #155 relates to exercising additional code paths in our regression tests. These include foreign file fetching, and creating/deleting tables.
- [ ] Issue #373 relates to "make check" failing on Mac 10.10.5 due to `libdir`.
- [x] Issue #561 relates to incorporating cstore_fdw related regression tests into our test suite.
- [ ] Issue #1912 relates to splitting some tests to another schedule

**Resolved**

- [x] Issue #133 relates to replacing \stage by `INSERT` to improve regression test runtime performance.
- [x] Issue #758 relates to adding regression tests to include queries with ``WHERE distribution column = NULL``.
- [x] Issue #795 adds regression tests for the MX project and queries from workers.
- [x] Issue #346 notes that our regression tests take minutes to run. The issue aims to reduce this runtime.
- [x] Issue #870 relates to adding regression tests to exercise queries that have non-relational filter clauses.
- [x] Issue #877 talks about adding Postgres as a regression test target for Citus.
- [x] Issue #345 talks about a semi-related issue that comes up when our regression tests run in an environment where worker nodes have high load. In that case, Citus might emit warning messages that break the regression tests.
- [x] Issue #323 changes the default policy for \stage. This makes our regression tests' output platform independent.
- [x] Issue #302 highlights a small fix in regression tests. We previously didn't have native support for hash partitioned tables in Citus and manually added lines to change partition method. We can now fix this.
- [x] Issue #275 considers rewriting certain regression tests to remove variant files that we added.
- [x] Issue #271 relates to manually setting shardId and jobId sequences in regression tests -- this will make it easier for us to reorder our regression tests and add new ones.
- [x] Issue #148 relates to the regression test worker_check_invalid_arguments failing on some platforms.
- [x] Issue #298 notes that we now have a pg_regress_multi script that removes the need for multi_task_tracker_executor.conf and binary_worker_copy_format.conf.
- [x] Issue #297 evaluates removing postgresql-hll (HyperLogLog extension) regression tests.
- [x] Issue #92 relates to using variable interpolation in regression tests to fix hardcoded paths.

**Comment by ozgune** [comment]
I'm updating this issue to better track open and resolved issues. The following issues related to regression tests and have been **fixed**:

* Issue #346 notes that our regression tests take minutes to run. The issue aims to reduce this runtime.
* Issue #345 talks about a semi-related issue that comes up when our regression tests run in an environment where worker nodes have high load. In that case, Citus might emit warning messages that break the regression tests.
* Issue #323 changes the default policy for \stage. This makes our regression tests' output platform independent.
* Issue #302 highlights a small fix in regression tests. We previously didn't have native support for hash partitioned tables in Citus and manually added lines to change partition method. We can now fix this.
* Issue #275 considers rewriting certain regression tests to remove variant files that we added.
* Issue #271 relates to manually setting shardId and jobId sequences in regression tests -- this will make it easier for us to reorder our regression tests and add new ones.
* Issue #148 relates to the regression test worker_check_invalid_arguments failing on some platforms.

**Comment by furkansahin** [comment]
- Issue #1842 suggests that we should add some tests with large number of shard_counts.
