### ISSUE TITLE
Release 9.3.2 Checklist

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#3933]
## Several things to note here

These instructions assume you have `$VERSION`, `$PROJECT`, and `$REPO` environment variables set in your shell (e.g. `9.3.0`, `citus`, and `citus`). With those set, code from most steps can be copy-pasted.

**After this checklist, you're still not done: open a release checklist in Enterprise and release there, too!**

# Prepare CHANGELOG
- [ ] Run `prepare_changelog.pl $PROJECT $VERSION <earliest_date>` on `$REPO` directory, and check the following:
  - [x] All items are listed in `CHANGELOG`
  - [x] The new entries are in both `master` and `release-x.y`
  - [x] There are no missing entries
  - [x] The lengths of items do not exceed 78 characters
  - [ ] The items are in ordered in terms of their importance
  - [x] All the items are present simple tense
  

# Prepare Release Branch
- [x] Run `prepare_release.pl $PROJECT $VERSION` on `$REPO` directory, and check the following:
  - [x] `configure.in` `configure` and `multi_extension.out` files are updated with the latest version
  - [ ] Ensure all needed changes are in the relevant `release-x.y` branch. `git log --cherry-pick --no-merges release-x.y...master` can be helpful.
- [x] Get _complete_ approval for the commit you're tagging before creating or pushing any tags. Tags should be immutable, so do **not** proceed to the next step until you're sure you have _everything_ you want in your release branch
- [x] Use `git tag -a -s v$VERSION` to create an annotated, signed tag for the release. Summarize the release in the one-line tag annotation (beneath 52 characters). Push the tag with `git push origin v$VERSION`
- [x]  Ensure that tag points to the release branch by using the following

$ git rev-parse tags/vX.Y.Z
\<commitId>
$ git branch --contains \<commitId>
release-X.Y

- [x] Visit the project's releases page (e.g. `open https://github.com/citusdata/$REPO/releases`)
  - [x] Create a new release object for your git tag (i.e. `v$VERSION`). Leave the description blank (it will auto-fill with the tag description)
