### ISSUE TITLE
Not expose citus local tables: Auto conversion from/to postgres to/from citus local tables for foreign keys

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#4415]
We don't want to expose citus local tables to users not to make things more complex.
For this reason, we decided to enable foreign keys **between postgres tables and reference tables** by **silently converting** postgres tables to a citus local tables before defining foreign keys.

-------

I wanted to document rough road-map while implementing the prototype, readers can consider each item as a seperate pull request:
- [x] **Implement on master/** Infrastructure to detect foreign key connected relations. #4439 
- [x] **Seperate feature on master/** Add cascade (on foreign key) option to `undistribute_table` #4457
- [x] **Seperate feature on master/** Add cascade (on foreign key) option to `create_citus_local_table` #4462

Above two items would also be benefical for unit testing.
They will also implement #4378 for those two udf's (and probably also for `create_reference_table` in future)

- [x] Enable reference/distributed table creation from citus local tables #4489
- [x] Intercept `ALTER TABLE ADD FOREIGN KEY` commands involving postgres tables and reference (or citus local) tables, automatically convert postgres tables involved in this command _-and the other postgres tables that those postgres tables are connected via their foreign key graphs-_ to citus local tables. #4479
- [x] Introduce a guc to enable/disable this feature #4480 
- [x] Do the same for `CREATE TABLE local table (col REFERENCES reference(or citus local) table)` commands. #4480
- [x] Do the same for `SELECT create_reference_table('%s')` commands where table has a foreign key relationship with local tables #4539 
- [x] Intercept ddl commands dropping foreign keys from citus local tables.
If citus local table wouldn't have any more foreign keys to reference tables via it's foreign key graph, then automatically convert this citus local table _-and the other citus local tables that it is connected via its foreign key graph-_ back to postgres table after dropping foreign key. #4538

Also made bunch of changes to hide `citus local table` detail from users:

- [x] Not mention citus local tables in error messages: #4579
- [ ] Replace `create_citus_local_table` with `citus_add_local_table_to_metadata` #4573

**Comment by onurctirtir** [comment]
Noting some questions/items in order not forget to address them:

* Should we do `s/citus local/local/` in error messages ?
* Intercept `create_reference_table` commands and take action like we do in `ALTER / CREATE TABLE commands` ?
* Don't validate foreign keys that we drop & re-define
* Overall behavior should be disabled when coordinator is not added to metadata ?
* Don't forget to remove create_citus_local_table udf in the end, or something else ?
