### ISSUE TITLE
Release checklist for 10.0.6

### ISSUE THREAD

**Issue by hanefi** [citusdata/citus#5463]
# Patch Release checklist

Note that this checklist contains a modified version of the checklist we usually have.

## Several things to note here

These instructions assume you have `$VERSION`, `$PROJECT`, and `$REPO` environment variables set in your shell (e.g. `9.5.10`, `citus`, and `citus`). With those set, code from most steps can be copy-pasted.

**After this checklist, you're still not done: open a release checklist in Enterprise and release there, too!**

# Prepare CHANGELOG
- [x] Go over all commits in the release branches, both community and enterprise
	- [x] Contact with authors if there are any commits that are in one branch only.
	- [x] Go over all the PRs and gather changelog items manually.
- [x] Check the following:
  - [x] All items are listed in `CHANGELOG`
  - [x] The lengths of items do not exceed 78 characters
  - [x] The items are in ordered in terms of their importance
  - [x] All the items are present simple tense
  - [x] The new entries are in both `master` and `release-x.y`

# Prepare Release Branch
- [x] Update the following files with the latest version
	- [x] `configure.in`
	- [x] `configure`
	- [x] `multi_extension.out`
	- [x] `multi_extension_0.out` if it exists on the branch.
- [x] Ensure all needed changes are in the relevant `release-x.y` branch. `git log --cherry-pick --no-merges release-x.y...master` can be helpful.
- [x] Get _complete_ approval for the commit you're tagging before creating or pushing any tags. Tags should be immutable, so do **not** proceed to the next step until you're sure you have _everything_ you want in your release branch

# Create the tag.

- [x] Use `git checkout release-X.Y && git pull && git tag -a -s v$VERSION` to create an annotated, signed tag for the release. Summarize the release in the one-line tag annotation (beneath 52 characters).
- [x]  Ensure that tag points to the release branch by using the following
```bash
$ git branch --contains `git rev-parse tags/vX.Y.Z`
* release-X.Y
```
You might also want to use `git log --oneline --decorate --graph --all`.

- [x] Push the tag with `git push origin v$VERSION`

## If this is a patch release for the latest major version, do the following:

- [ ] Visit the project's releases page (e.g. open https://github.com/citusdata/$REPO/releases)
- [ ] Create a new release object for your git tag (i.e. v$VERSION). Leave the description blank (it will auto-fill with the tag description)
