### ISSUE TITLE
Django Support

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#549]
Issues:
- [x] #511 It creates tables with the SERIAL data type, which we don't currently support
  
  Workaround: It fails because some sequences don't exist on the workers, create those sequences manually. 
- [x] #213 Running functions on the master. When inserting timestamps it casts strings to timestamptz, and that cast isn't IMMUTABLE
- [x] #505 Single statement transaction support. 
- [x] #242 support for RETURNING
  
  Workaround:
  
  ```
  from django.db import connection
  connection.features.can_return_id_from_insert = False
  ```
- [x] #698 Confusing error message when trying to setup a FOREIGN KEY: (edited to add issue number)
  
  ```
  django.db.utils.NotSupportedError: alter table command is currently supported`
  DETAIL:  Only ADD|DROP COLUMN, SET|DROP NOT NULL, SET|DROP DEFAULT and TYPE subcommands are supported.
  ```
  
  Probably better would be to say "we don't support FOREIGN KEY constraints"
  
  Also, maybe we could support FOREIGN KEY constraints which hit the partition column? That sounds doable from the master, if not slow.
- [x] #687 Doesn't specify a value for the partition column, which we require to be non-constant (Just uses a SERIAL and relies on the DEFAULT)

**Comment by lfittl** [comment]
@lithp I'd be curious to see how this list has changed now with 5.2 being feature complete. I've updated the Rails list (https://github.com/citusdata/citus/issues/595), and similarly I think we can mark the following items from the above list as done:

* #511 / SERIAL
* #242 / RETURNING
* #505 / Single statement transaction support
* #213 / Running functions on the master

I've also created https://github.com/citusdata/citus/issues/687 which might be the same issue as "Doesn't specify a value for the partition column, which we require to be non-constant (Just uses a SERIAL and relies on the DEFAULT)" ?

**Comment by lfittl** [comment]
Updated this issue together with @ozgune.

@begriffs please feel free to add more based on your experience with Django :)

**Comment by BrnoPCmaniak** [comment]
Just workaround for #698 for anybody coming across this:
https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.ForeignKey.db_constraint

**Comment by ziXet** [comment]
I think the only issue that is left from the list is #687 .

**Comment by ziXet** [comment]
I think the only issue that is left from the list is #687

**Comment by marcocitus** [comment]
We've checked all the boxes in the issue.

@saicitus Are there additional things we need to cover on our end to enable Django support?

**Comment by saicitus** [comment]
Library to help with architecting a multi-tenant database in django. It is not yet released, work in progress:
https://github.com/citusdata/django-multitenant

**Comment by ozgune** [comment]
@saicitus -- Do you have any updates on the Django Multi-tenant library?

**Comment by ozgune** [comment]
We recently added migration steps for Django into our docs: https://docs.citusdata.com/en/v6.2/migration/transitioning.html#django

With that, I'm closing this issue.
