### ISSUE TITLE
Metadata Sync Fails in Regression Tests

### ISSUE THREAD

**Issue by halilozanakgul** [citusdata/citus#5585]
These are the remaining tests we still need to turn metadata syncing on.

- [x] isolation_schedule
   - [x] isolation_update_node #5779 
   - [x] isolation_update_node_lock_writes #5779 
   - [x] isolation_replicate_reference_tables_to_coordinator
   - [x] isolation_reference_copy_vs_all #5790 
   - [x] isolation_ref2ref_foreign_keys #5791 
   - [x] isolation_multiuser_locking https://github.com/citusdata/citus/commit/923bb194a47ab3880acb4f06dc61b36c7cf4ef19
- [x] failure_schedule @onderkalaci  via https://github.com/citusdata/citus/pull/5606
   - [x] failure_create_distributed_table_non_empty 
   - [x] failure_create_table
   - [x] failure_single_select
- [x] operations_schedule @onderkalaci 
   - [x] shard_rebalancer https://github.com/citusdata/citus-enterprise/pull/729
- [x] multi_1_schedule
   - [x] single_node @onderkalaci  #5595
   - [x] single_node_truncate @onderkalaci #5595 
   - [x] multi_row_router_insert @onderkalaci #5596
   - [x] Foreign Table Bug @agedemenli 
      - [x] multi_generate_ddl_commands
      - [x] multi_repair_shards
      - [x] multi_create_shards
      - [x] multi_colocation_utils
      - [x] citus_local_tables
      - [x] mixed_relkind_tests

Enterprise Fails 
- [x] enterprise_failure_schedule @onderkalaci 
   - [x] failure_tenant_isolation https://github.com/citusdata/citus-enterprise/pull/727
- [x] enterprise_isolation_logicalrep_1_schedule @onderkalaci 
   - [x] isolation_logical_replication_multi_shard_commands
- [x] enterprise_isolation_schedule
   - [x] isolation_tenant_isolation
   - [x] isolation_shard_move_vs_start_metadata_sync

**Comment by onderkalaci** [comment]
@halilozanakgul can you please close the issue after double checking that we don't have any non-mx tests left?

(For reference, we have a non-mx schedule on the arbitrary config)

**Comment by halilozanakgul** [comment]
All the items are addressed.
