### ISSUE TITLE
Rails/ActiveRecord Support

### ISSUE THREAD

**Issue by lfittl** [citusdata/citus#595]
## Overall status

Rails works well with Citus, this just lists a few minor features which are typically not a blocker.

We recommend using [activerecord-multi-tenant](https://github.com/citusdata/activerecord-multi-tenant) for full support of ActiveRecord operations.

## Must-have tasks

Mirroring #549, this is what we'd need in order to support Rails better, when using the default ActiveRecord ORM.
- [x] Fixed in 5.2: #627 Transactions don't work on distributed tables
- [x] Fixed in 5.2: #242 Support for RETURNING
  
  Workaround: Add the following to database.yml:
  
  ``` yml
  default: &default
    ...
    insert_returning: false
  ```
- [x] Fixed in 5.2: #511 Sequences (and SERIAL) are used by default for the `id` column
- [x] Fixed in 6.0: #668 DDL is not supported inside transactions
- [x] #306 Support for PREPARE statements with parameters - Rails by default runs everything in named prepared transactions
  
  Workaround: Disable like this in database.yml:
  
  ``` yml
  default: &default
    ...
    prepared_statements: false
  ```

## Nice-to-have tasks

- [x] #1080 Support DISABLE/ENABLE TRIGGER ALL on distributed tables

  This makes Rails' disable_referential_integrity method fail, which is used by libraries like database_cleaner between test runs.
* [x] #687 Support evaluating functions on master to determine partition column value
  
  This is an edge case of #511 when you e.g. have a `customers` table and want to shard on `customer_id`, but also have the server determine the value for `customer_id` when inserting.
  
  Workaround: Generate the ID on the client side (or fetch it from the server with a separate `SELECT nextval('example_id_seq'::regclass)`), and then pass the value in with the `INSERT` statement.

* [x] #1230 Citus Query Planner is unable to handle 1=0 conditions

  This will cause Model.none to fail, e.g. when that scope is merged into a query.

- [x] #866 Schema-only pg_dump (i.e. `rake db:migrate`) shows a few (harmless) warnings related to dependency resolving - would be nice if they wouldn't be there
  
  ```
  pg_dump: [sorter] WARNING: could not resolve dependency loop among these items:
  pg_dump: [sorter]   TABLE impressions  (ID 240 OID 19654)
  pg_dump: [sorter] WARNING: could not resolve dependency loop among these items:
  pg_dump: [sorter]   TABLE clicks  (ID 241 OID 19661)
  ```

- [x] #1493 Add support for SAVEPOINT / ROLLBACK TO SAVEPOINT

  This produces issues when doing `Model.transaction { OtherModel.transaction { .. } }` - typically seen with unit tests that use transactional mode, as an alternative one can use truncation instead for these tests (e.g. using database_cleaner)
- [x] #779 **(Real-time analytics model only)** IN (..) shows a warning, suggesting to use OR if you want SELECTs to only hit the right shards - this is harmless, but it would be nice if we supported pruning down to the correct shards for IN as well

---

Note that https://github.com/citusdata/citus-example-ad-analytics is a fully working Rails example app that uses both local and distributed tables (hash partitioned)

## Follow-up tasks

These items are tracked in their own issues:

* [ ] #1236 SELECT ... FOR UPDATE is not supported for router-plannable queries

  This causes `with_lock` to fail, even in the multi-tenant model.

- [ ] #1131 **(Real-time analytics model only)** Modification commands (e.g. `record.update!(field: 'value')`) might open transactions involving multiple tables or shards. Right now, when running in a transaction, any DML command that opens a connection to a second node will error out.

**Comment by ozgune** [comment]
@lfittl -- I had a quick question on IN (...) support. Could you copy/paste an example query that errors out?

**Comment by lfittl** [comment]
@ozgune Summarizing the conversation we had in person on this:

Any query that accesses multiple shards, and uses IN (...) on the partition_key, will show a warning suggesting them to use `OR` instead, because we always send IN (...) to all shards, instead of pruning down to a subset based on the IDs.

Somebody not knowing this in detail might be confused about that warning - but really its quite harmless. I just listed it because it seemed like something to keep in mind, and potentially worth supporting in the future (i.e. treating `partition_id IN (1, 2, 3)` the same as `partition_id = 1 OR partition_id = 2 OR partition_id = 3`)

**Comment by lfittl** [comment]
@ozgune I've also restructed the issue description to split it into must-have tasks, and nice-to-have tasks.

In particular, having a multi-tenant model in mind, once #687 and #306 are solved we can consider closing this issue.

**Comment by anarazel** [comment]
@lfittl Ticket the prepared-statement box - hope that's right.

**Comment by lfittl** [comment]
@anarazel Yup, thats great - thanks for the effort on fixing this, and updating the issue here as well.

**Comment by ozgune** [comment]
@lfittl -- I had a quick question on IN (...) statements on the partition key. We have two issues, #923 and #779 that mention IN (...) statements. Are these the same issue as the one you're mentioning?

**Comment by lfittl** [comment]
@ozgune Yes - although #779 matches it most closely (i.e. Rails would produce `IN (...)` not `ANY({...})`

**Comment by lfittl** [comment]
@ozgune Given that the remaining issues are not required for most use cases we are seeing, I'm closing this issue and suggest we track the two remaining items (`SELECT ... FOR UPDATE` and unrestricted cross-shard modifications) in their own issues.
