### ISSUE TITLE
Flaky test counts between April 25 to May 26

### ISSUE THREAD

**Issue by hanefi** [citusdata/citus#5975]
This issue aims to capture the current state of the flaky tests, and coordinate fixes.

I created a summary on the failures on master branch since last 30 days. See the test name followed by the number of failures in the last 30 days in parentheses

## Regression tests
- [ ] `rollback_to_savepoint` (5)
- [ ] `columnar_first_row_number` (2)
- [ ] `distributed_triggers` (1) not fully fixed by #5894

## Isolation tests
- [ ] `isolation_replicate_reference_tables_to_coordinator` (8)
- [ ] `isolation_transaction_recovery` (1)
- [ ] `isolation_distributed_deadlock_detection` (1)
- [ ] `isolation_multi_shard_modify_vs_all` (1)
- [ ] `isolation_ref2ref_foreign_keys` (1)
- [ ] `isolation_hash_copy_vs_all` (1)

## Failure tests
- [ ] `failure_insert_select_repartition` (14)
- [ ] `failure_setup` (7)
- [ ] `failure_single_select` (1)

## Others
- [ ] `check-merge-to-enterprise` (4)

## Failures that happened before fixes were merged
- [x] `global_cancel` (2) #5948
- [x] `isolation_drop_alter_index_select_for_update_on_mx` (2) #5910
- [x] `isolation_ddl_vs_all` (1) #5910
- [x] `isolation_select_vs_all` (1) #5910
- [x] `isolation_select_vs_all_on_mx` (1) #5910

**Comment by hanefi** [comment]
This issue is a continuation of #5909

**Comment by onurctirtir** [comment]
Probably not applicable anymore as we don't see any more occurrences of them.
