### ISSUE TITLE
Reference tables: Parent issue

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#879]
We currently enable reference tables in an indirect manner: if the user specifies a shard count less than `citus.large_table_shard_count`, we assume during query planning that the table can be broadcasted. This introduces confusion and we should enable creating reference tables in an intuitive way.

Other distributed databases also have this concept. They either have the notion of a replicated, reference, or dimension table; or ask the user to use an "all" distribution method to replicate a table to all the nodes.

I'm creating this issue to track a proper implementation of reference tables that works both on Citus Community Edition and Cloud. I'm also documenting other questions or issues that came up in relation to reference tables below. 

We have the following issues related to reference/broadcast tables. In an ideal scenario, we resolve as much of the following issues with this upcoming implementation.

- [ ] #1787 discusses removing broadcast related state, state transitions, and logic from real-time and task-tracker executors.
- [ ] #1260 discusses removing data fetches during distributed joins.
- [ ] #968 discusses foreign keys for reference tables. In MVP, we skip foreign keys since they are tricky to implement.
- [ ] #527 notes that our distributed `EXPLAIN` fails with queries that have broadcast joins.
- [ ] #638 notes that we have logic related to caching that's no longer relevant. With #594, we can now remove this logic.
- [ ] #292 notes that we have obsolete code paths related to broadcast joins. Now that we have `\stage` deprecated, we could potentially remove related data fetching functions.
- [ ] #458 talks about a bug that we have in our codebase that triggers with repartitioned joins and replication factor = 1. The underlying reason for this bug is that we assumed broadcasted tables can have more than 1 shard. If we lock reference tables to 1 shard, we could potentially resolve this bug (reported by Cloud).
- [ ] #253 talks about a code path related to shard caching (for broadcast tables) that may not be covered by our regression tests. This was one of the few code paths that showed no coverage when we ran code coverage tools.
- [ ] #56 talks about a bug related to broadcast joins. If we have a node failure during shard caching, we may return stale results to the caller.

The following items are **now resolved**.

- [x] #1328 talks about expanding our transaction support for transactions that touch reference and distributed tables.
- [x] #965 Discusses a deadlock with DDL on reference table with concurrent multi-shard modification query including a reference table.
- [x] #827 captures the discussion on introducing a new API to create reference tables (v6.0).
- [x] #760 notes that the current implementation for broadcasted tables runs into challenges with the multi-tenant use case when deployed on the Cloud.
- [x] #715 talks about allowing primary or unique key constraints on non-partition column for tables that have a single shard.
- [x] #966 Compares different trade-offs among transactional behaviour for reference table DML
- [x] #967 Discusses MX integration for reference tables
- [x] #969 Discusses how to represent reference tables in the metadata
- [x] #970 Discusses the upgrade path for existing reference tables
- [x] #971 Discusses the behaviour while adding a new node
- [x] #972 Discusses the behaviour while removing a new node
- [x] We're adding automatic propagation of foreign key constrains for colocated tables in #698. We should evaluate how/if we handle foreign key constraints for reference tables. See #968.
- [x] We should evaluate whether we use 1PC/2PC to propagate changes to reference tables. On the Cloud, we can easily increase `max_prepared_transactions` (we set this to 300). On the Community Edition, this may require more work.
- [x] We have code in the join order planner, physical planner, real-time executor, and task-tracker executor to fetch shards between nodes for broadcast joins.
- [x] #1200 Discusses decoupling `master_add_node` and reference table replication.
- [x] #1609 Discusses relaxing a restriction on the reference tables when used in subquery pushdown

**Comment by onderkalaci** [comment]
Below, I tried to summarize the next steps and open questions for reference table implementation:

## Phase 1: Represent reference tables in the metadata
This item requires the most comprehensive changes. With a short summary:
* Creates a new partition method (i.e.,`DISTRIBUTE_BY_ALL`  -- name is TBD)
* This new partition method does not have any partition column. In citus code, we always assume that any distributed table has a distribution column. In this phase, we need to change that understanding. 
* The main issue for this is #969. After this phase, we expect proper reference tables to support almost all existing Citus capabilities.
* Make sure that issues #527 and #56 fixed
* I'll own and implement this feature.

## Phase 2: Improve reference tables to support new features & fix any bugs
This item aims to improve the user experience of reference tables
* Do not allow foreign keys for 6.1. Fixes #968 
* Provide a path to upgrade existing reference tables to the explicit reference tables. Fixes #970 
* Handle node add/remove functionality with reference tables. Fixes #971 and #972 
* Allow any kind of unique constraints. Fixes #715.
* Ensure MX integration is good. Fixes #967.
* It is possible to hand some of the tasks to other devs if needed.

## Phase 3: Implement 2PC data propagation for reference table
This item aims to implement 2PC within the router executor. We decided to leave this item as the last given that there is a possibility that Connection management API might already be shaped, and we could utilize that instead of implementing 2PC on router executor. Also, though not the intended behavior, without 2PC the reference tables could still work and even if they are marked as inactive there is a way to recover from it (`repair shards`).
* Implements / Fixes #966.
* Fix a certain deadlock with reference tables. Fixes #965.
* I'll own and implement this part.


## Open product / user experience questions:
@ozgune / @marcocitus  do you have any comments on the followings? Thanks!
### SQL Coverage
* In an ideal world, we'd expect reference tables to be drop-in replacement for PostgreSQL tables in terms of the SQL coverage. However, I have some reservations on this.
   * For instance, we could support multi-row `INSERT` statements and subqueries in `WHERE` clause of `UPDATEs`.
   * This may require some extra changes in the code. Also, given that I'm not an expert of features that Citus currently does not support, this may require a lot of testing on my side.
   * Similarly, we have to ensure that deparsing of those queries works expected.
   * Lastly, this may require some new locking codes that are different than what we have in the code. For instance, what happens if there exists UPDATEs with CTEs. We *may* need to traverse CTE expressions and find required tables etc.
* In summary, the user experience would be `What we have in Citus` + `Remove limitations with partition column values`
   * For instance, the user would be able to `INSERT` any row that misses any of the columns. (Note that, in regular Citus queries, it has to include the partition column).
* Is the above approach good to go?

### Adding nodes, creating reference tables and 2PC
* Since we're going to use 2PC for reference tables, we need to ensure that `max_prepared` transactions on the workers `> 0`
* What I suggest is:
  * When `create_reference_table` issued, go and check whether all workers have `max_prepared > 0`. Else, error out with a **nice** error message.
  * When `master_add_node()` issued, if there are already reference tables in the cluster, check `max_prepared > 0`on the new node. Else, error out with a **nice** error message.
* The above aims to error out early and gracefully instead of erroring out once a modification query is issued. Is the above approach good to go?

### Updating existing reference tables and removing caching related codes
* I suggest we provide a UDF to update existing reference tables. And, this action is done manually on the tables one-by-one. See #970. (The other method could be do it automatically during upgrade, which seems too much overhead for an upgrade.)
* This means that the users wouldn't have to upgrade to the new class of reference tables.
* Finally, this means that we have to keep the caching related codes for maybe 1-2 more releases. 
* Does that sound OK to you as well?

### Name of the new distribution method
* I think `DISTRIBUTE_BY_ALL` is intuitive.
* The other options mentioned in other issues `DISTRIBUTE_BY_NONE` and `DISTRIBUTE_BY_REFERENCE`. I think the former is confusing, which makes me feel that the table is not distributed.
* Do we have any other alternatives? Any preference?
* Also, note that we use a single `char` in the code to represent distribution methods. We already reserved `r` for `DISTRIBUTE_BY_RANGE` and `a` for `DISTRIBUT_BY_APPEND`. So, for now, I had to pick `l` for `DISTRIBUTE_BY_ALL`. Please give me some ideas on this as well.

**Comment by ozgune** [comment]
@onderkalaci -- I'm adding my notes to this issue. If we have any open questions by next week, it may be worth hopping on a quick call with @marcocitus and @samay-sharma.

## SQL Coverage

For the initial version, skipping over this additional functionality sounds good to me. It may be worth checking with @anarazel how hard he anticipates this to be and then opening an issue tracking this functionality.

## Adding nodes, creating reference tables and 2PC

Adding a check to see if worker nodes have ``max_prepared_transactions`` set to > 0 sounds good. That said, I had a usability question.

I remember @anarazel mentioning that we could increase ``max_prepared_transactions``'s default value  during Citus initialization. Is that still the case? If so, could we up this setting's value by default? For the actual value, Citus Cloud sets this value to 300 in config.

## Updating existing reference tables and removing caching related codes

Could you elaborate a bit more on this proposal? What does updating existing reference tables mean?

My understanding is that, customers who use reference tables in production, manually set the ``shard_replication_factor`` to the number of machines. Could we confirm that with @samay-sharma and @saicitus?

On keeping caching related code paths for another few releases, I'm slightly hesitant. Most likely, whatever stays after this release will stay there for good. 😄  We know that certain code paths are obsolete in v6.0 (#638) or will be with this release (#594).

How much effort would it be to detect if we have an incompatible "broadcasted table" and ask the user to upgrade to the new reference tables?

## Name of the new distribution method

Do we expect this name to be visible to users? Or is this something that only lives in the metadata? If this name won't be visible to users, I'm cool with an intuitive name that you agree on.

**Comment by anarazel** [comment]
Hi,

On 2016-11-30 23:54:07 -0800, Önder Kalacı wrote:
> ## Phase 3: Implement 2PC data propagation for reference table
> This item aims to implement 2PC within the router executor. We decided to leave this item as the last given that there is a possibility that Connection management API might already be shaped, and we could utilize that instead of implementing 2PC on router executor. Also, though not the intended behavior, without 2PC the reference tables could still work and even if they are marked as inactive there is a way to recover from it (`repair shards`).
> * Implements / Fixes #966.
> * Fix a certain deadlock with reference tables. Fixes #965.
> * I'll own and implement this part.

Let's please wait with implementing this until the connection management
et al. stuff has landed.

**Comment by sumedhpathak** [comment]
Needs documentation at https://github.com/citusdata/citus_docs/issues/229.

**Comment by sumedhpathak** [comment]
@onderkalaci Is this also pending #1105?

**Comment by onderkalaci** [comment]
> @onderkalaci Is this also pending #1105?

#1105 and #1103 (mx integration)

**Comment by sumedhpathak** [comment]
@onderkalaci  Now that #1105 and #1103 are both closed, can we close this issue?

**Comment by onderkalaci** [comment]
> @onderkalaci Now that #1105 and #1103 are both closed, can we close this issue?

@sumedhpathak I'm OK with closing the issue. But, there are some issues which we've not closed and the explanation is [here](https://github.com/citusdata/citus/issues/527#issuecomment-273051914). I need a second opinion on such issues.

**Comment by metdos** [comment]
@onderkalaci, we track #527 separately, so we should be ok to close this. What do you think?

**Comment by ozgune** [comment]
@metdos / @onderkalaci -- I removed the v6.1 milestone from this issue and also updated the original comment with resolved points.

We still have a few issues related to our previous implementation around broadcasted tables. I'm therefore renaming this to a "parent issue" on reference tables -- so that we can track related issues in one place.

**Comment by serprex** [comment]
#458 is the only outstanding issue here
